#!/usr/bin/env python3
"""
飞书配置诊断工具
"""

print("=" * 80)
print("飞书配置诊断")
print("=" * 80)

print("\n【2. 飞书开放平台配置检查清单】")
print("-" * 80)
print("\n请按以下步骤检查飞书开放平台配置：")
print()

print("步骤1: 检查事件订阅配置")
print("  1. 打开 https://open.feishu.cn/app")
print("  2. 进入你的应用")
print("  3. 点击左侧菜单「事件与回调」→「事件配置」")
print("  4. 确认以下配置：")
print()
print("     ⚠️  订阅方式: 必须选择「使用长连接接收事件」")
print("     ⚠️  事件列表: 必须包含以下事件：")
print("         • im.message.receive_v1 (接收消息)")
print()

print("步骤2: 检查权限配置")
print("  1. 点击左侧菜单「权限管理」")
print("  2. 搜索并开通以下权限：")
print()
print("     • im:message (获取与发送消息)")
print("     • im:message:group_at_msg (获取群组中@机器人的消息)")
print("     • im:chat (获取群组信息)")
print()

print("步骤3: 检查应用发布状态")
print("  1. 点击左侧菜单「版本管理与发布」")
print("  2. 确认应用状态：")
print()
print("     ⚠️  必须创建版本并发布")
print("     ⚠️  必须安装到测试租户")
print()

print("步骤4: 测试发送消息")
print("  1. 在飞书中找到你的机器人")
print("  2. 发送消息的方式：")
print()
print("     • 单聊: 直接给机器人发消息")
print("     • 群聊: 必须在群里@机器人")
print()

print("\n【3. 常见问题排查】")
print("-" * 80)
print()
print("问题1: 长连接已建立但收不到消息")
print("  原因: 事件订阅未配置或配置错误")
print("  解决: 确保选择了「长连接模式」并添加了 im.message.receive_v1 事件")
print()
print("问题2: 应用未发布")
print("  原因: 应用还在开发状态，未发布到租户")
print("  解决: 在「版本管理与发布」中创建版本并发布")
print()
print("问题3: 权限不足")
print("  原因: 缺少必要的权限")
print("  解决: 在「权限管理」中开通相关权限")
print()
print("问题4: 群聊消息不触发")
print("  原因: 群聊需要@机器人才能触发")
print("  解决: 在群里发送消息时@机器人")
print()

print("\n【4. 快速验证步骤】")
print("-" * 80)
print()
print("1. 在飞书开放平台，进入「事件与回调」→「事件配置」")
print("2. 确认订阅方式为「使用长连接接收事件」")
print("3. 点击「添加事件」，搜索并添加：")
print("   • im.message.receive_v1")
print("4. 点击「保存」")
print("5. 在「版本管理与发布」中创建版本并发布")
print("6. 在飞书中给机器人发送消息")
print()

print("\n【5. 验证配置是否生效】")
print("-" * 80)
print()
print("配置完成后，重新运行测试脚本：")
print("  python3 test_feishu_standalone.py")
print()
print("如果配置正确，发送消息后会看到：")
print("  🎉🎉🎉 收到飞书消息事件！🎉🎉🎉")
print()

print("=" * 80)
print("诊断完成")
print("=" * 80)
